### ISSUE TITLE
When your cursor sits somewhere for too long, it disappears.

### ISSUE THREAD

**Issue by mannyglover** [spyder-ide/spyder-vim#14]
The root of this is a Spyder editor problem rather than a spyder-vim problem, I think.  When your cursor is on a word for more than a second or two, it highlights this word and all other occurrences of this word in yellow.  Then spyder-vim's cursor totally disappears.  You have no idea where your cursor has disappeared too until you figure out this issue.  Then, when you've figured it out, you're still clueless when ever you pass through this word or another occurrence of this word.

**Comment by pwoosam** [comment]
I believe this is the same as issue #7?

**Comment by Nodd** [comment]
Yes it is. A workaround for now is to disable word highlighting.

**Comment by mannyglover** [comment]
Sorry about that.  I should have read the other issues first (especially since there aren't many).  Thanks.
