### ISSUE TITLE
Create a pypi package

### ISSUE THREAD

**Issue by mariacamilarg** [spyder-ide/spyder-vim#21]

**Comment by goanpeca** [comment]
Remember to work at normal hours! @mariacamilaremolinagutierrez

**Comment by ccordoba12** [comment]
@pwoosam, just so you know, I assigned @mariacamilaremolinagutierrez (one of our junior devs) to be in charge of this plugin and create an initial release for it.

We hope to count with you to review and merge her work :-)

**Comment by dalthviz** [comment]
Closing since v0.1.0 was already released :tada: and available from PyPI: https://pypi.org/project/spyder-vim/

**Comment by ccordoba12** [comment]
Pretty cool! Thanks @ok97465 for your help with that!
