### ISSUE TITLE
Create a conda recipe and package

### ISSUE THREAD

**Issue by goanpeca** [spyder-ide/spyder-vim#22]

**Comment by dalthviz** [comment]
Note: To be done after v0.1.0 is released

**Comment by dalthviz** [comment]
See https://github.com/conda-forge/staged-recipes/pull/20716

**Comment by ccordoba12** [comment]
Thanks @dalthviz!

**Comment by dalthviz** [comment]
Closing since the package is already available on conda-forge: https://anaconda.org/conda-forge/spyder-vim
