### ISSUE TITLE
Add tests to the project and CI Integration

### ISSUE THREAD

**Issue by mariacamilaremolinagutierrez** [spyder-ide/spyder-vim#24]

**Comment by ccordoba12** [comment]
@goanpeca, could give Cami a crash course on how she can start testing this project? Thanks :-)

**Comment by goanpeca** [comment]
@mariacamilaremolinagutierrez can we meet tomorrow? in the afternoon?

13:00 ?

**Comment by ccordoba12** [comment]
@andfoy, please use only Circle for now and add tests for Python 2.7, 3.5 and 3.6.

I already setup the right settings for this repo, so you should be good to go ;-)
