### ISSUE TITLE
Consistent naming with other spyder plugins

### ISSUE THREAD

**Issue by ghisvail** [spyder-ide/spyder-vim#27]
May I suggests to change the package name from `spyder.vim` to `spyder-vim`, to be consistent with other published plugins such as `spyder-unittest`?

FYI, the name `spyder.vim` suggests either a library laid out as `spyder/vim`, a namespaced package under the `spyder` umbrella, or a plugin for `vim`, neither of which is the case.

**Comment by ccordoba12** [comment]
Ok, will do. Thanks for the suggestion ;-)
