### ISSUE TITLE
I am unable to install spyder-vim by pip..PLZZZZ help

### ISSUE THREAD

**Issue by lihka1** [spyder-ide/spyder-vim#35]
Thanks in advance

**Comment by andfoy** [comment]
@lihka1 We haven't released Python packages yet. However, if you're installing from source, you can execute ``pip install .`` on the repo's root.

**Comment by andfoy** [comment]
Closing as duplicate of #33

**Comment by lihka1** [comment]
I installed from source and unable to see vim terminal....can you please help as i am a newbie..

**Comment by ayooshkathuria** [comment]
@lihka1 
'git clone https://github.com/spyder-ide/spyder-vim`
`cd spyder-vim` 
`pip install .`

Restart spyder, you will find a text field besides the word "vim" at the bottom of the editor. Here you can execute vim commands.
