### ISSUE TITLE
I installed spyder-vim from source and unable to see vim terminal....can anyone please help 

### ISSUE THREAD

**Issue by lihka1** [spyder-ide/spyder-vim#37]

**Comment by ccordoba12** [comment]
Press `Esc` in the Editor to see it.

**Comment by lihka1** [comment]
I tried but it's not working....can you help..
sorry for late response.
thanks in advance

**Comment by andfoy** [comment]
@lihka1 Could you please post a screenshot of what are you seeing right now?

**Comment by andfoy** [comment]
![imagen](https://user-images.githubusercontent.com/1878982/31950607-415e375a-b8dc-11e7-99a0-bab0519b311f.png)

Do you have any error message displayed on the internal console/bug report dialog?

**Comment by lihka1** [comment]
No

**Comment by lihka1** [comment]
What about this?
![screenshot from 2017-10-24 20-52-47](https://user-images.githubusercontent.com/25284480/31952202-b2a6f2aa-b8fd-11e7-8bbe-0def912d0a23.png)

**Comment by andfoy** [comment]
Wasn't this error already fixed on Spyder 3.2.3 @ccordoba12 @dalthviz?

**Comment by lihka1** [comment]
@andfoy  If I am removing those egg files I was not seeing any errors.

**Comment by andfoy** [comment]
Have you tried to install on a fresh anaconda environment?

**Comment by lihka1** [comment]
No, I didn't try

**Comment by lihka1** [comment]
It worked in a new environment!!!........thanks

**Comment by ccordoba12** [comment]
> Wasn't this error fixed on Spyder 3.2.3

Yep, it was.

**Comment by ccordoba12** [comment]
But I think we are discarding `egf_FILES`. @andfoy, please open a PR in Spyder to discard that ending too.
