### ISSUE TITLE
not working on spyder3.2.4

### ISSUE THREAD

**Issue by Enrico68** [spyder-ide/spyder-vim#38]
I have just installed using git with the following command `pip3 install .`  When I press <kbd>ESC</kbd> cursor doesn't change status . I am using Python 3.6.3 64bits, Qt 5.9.1, PyQt5 5.9 on Darwin

**Comment by ccordoba12** [comment]
Thanks for reporting. @andfoy?

**Comment by hayai-M5** [comment]
It's working for me after manually copying the plugin:
cp -pR build/lib/spyder_vim ~/.spyder-py3/plugins/

**Comment by Enrico68** [comment]
Yes, it works !
