### ISSUE TITLE
How to start using spyder-vim?

### ISSUE THREAD

**Issue by boonstar** [spyder-ide/spyder-vim#40]
Hi Guys,

I've installed spyder-vim. Expected it to work like a vim in the editor. But it still behaves like normal.

I've searched through all the documentations, but did not find any clue to "start" using it. Is there any start command that I've missed?

Thanks.

**Comment by matheusfillipe** [comment]
Also I've installed running `python setup.py install`, and when I esc on the editor nothing happens.

**Comment by ccordoba12** [comment]
Sorry, this plugin is not ready yet to be used. We'll try to come back to it before the end of the year.

**Comment by hafner** [comment]
Seems like a note stating that should be somewhere more prominent. Would have saved me a bunch of trouble trying to get it working...

**Comment by ccordoba12** [comment]
@CAM-Gerlach, please don't forget to help me with when you're fixing the Readme of this repo.

**Comment by CAM-Gerlach** [comment]
Yes indeed, I was actually working on the Spyder-Vim readme as we speak, and that's the main reason for including the funding status section in the readme as discussed in spyder-ide/spyder-terminal#143, The heading of the section is ``Plugin development paused until Spyder 4 release`` and the first lines discusses the development freeze and the planed Spyder 4 release window. I'll note it fixes this issue in the forthcoming PR.

**Comment by ccordoba12** [comment]
Thanks @CAM-Gerlach!

**Comment by mochsner** [comment]
@MaxGyver83 were you ever able to get this working? There doesn't seem to be any recent active development, but there's definitely been some changes since you posted.

**Comment by MaxGyver83** [comment]
@mochsner : No, I wasn't. I switched to VSCodium + [vscode-neovim](https://github.com/asvetliakov/vscode-neovim). But currently, I just use vim for writing Python code.

**Comment by ccordoba12** [comment]
@ok97465, after installing this plugin and restarting Spyder, users shouldn't need to do anything else to use it, right?

**Comment by ok97465** [comment]
> @ok97465, after installing this plugin and restarting Spyder, users shouldn't need to do anything else to use it, right?

Yes, that's right.

**Comment by ccordoba12** [comment]
Thanks @ok97465. I pushed PR #82 with a small `Usage` section to the Readme to address this issue.
