### ISSUE TITLE
Is this project still alive?

### ISSUE THREAD

**Issue by nnnewb** [spyder-ide/spyder-vim#42]

**Comment by ccordoba12** [comment]
I'm sorry, all our third-party plugins are in standby until we finish Spyder 4. However, you're welcome to submit pull requests to finish this plugin.

**Comment by nnnewb** [comment]
> I'm sorry, all our third-party plugins are in standby until we finish Spyder 4. However, you're welcome to submit pull requests to finish this plugin.

i see, thank you for your kind reply.
