### ISSUE TITLE
Vim in Spyder 4

### ISSUE THREAD

**Issue by camilomarino** [spyder-ide/spyder-vim#43]
I wanted to know if this plugin is compatible with spyder 4.

I installed it in spyder 3 and it works correctly, but when I install it in spyder 4 the vim bar does not appear to me.

**Comment by ccordoba12** [comment]
Unfortunately this plugin has not been to Spyder 4, sorry.

**Comment by goanpeca** [comment]
Hi @camilomarino. If you would to help update the plugin to work with Spyder v4, let us know. We are always looking for helping hands, as our time is limited.

Cheers!
