### ISSUE TITLE
Regex expression is not working with search command.

### ISSUE THREAD

**Issue by ok97465** [spyder-ide/spyder-vim#53]
Regex repression is not recognized when I use "/" or "?" command.

I think that QRegExp is missing in the line for find.

https://github.com/spyder-ide/spyder-vim/blob/62ffd574c3e8a32c3beebcc6e938c23b2d79bef0/spyder_vim/vim_widget.py#L171

https://github.com/spyder-ide/spyder-vim/blob/62ffd574c3e8a32c3beebcc6e938c23b2d79bef0/spyder_vim/vim_widget.py#L181-L182

Thank you for working on this project. I am using it very usefully. Have a nice day.

**Comment by ccordoba12** [comment]
@bgallois, what do you think?

**Comment by bgallois** [comment]
@ccordoba12 @ok97465, your right, I have forgotten a QRegExp. I will correct it and add a test for the regex expression case.
