### ISSUE TITLE
_get_line() method is not working at the last line

### ISSUE THREAD

**Issue by ok97465** [spyder-ide/spyder-vim#58]
_get_line() method is not working at the last line. So "f", "F", "^"... which uses _get_line is not working at the last line.

https://github.com/spyder-ide/spyder-vim/blob/50fa9bd71cdc98ca6de026a859f07135e4031b7a/spyder_vim/vim_widget.py#L144-L155

Thank you.

**Comment by goanpeca** [comment]
Hi @ok97465 thanks for the report.

I guess another one for @bgallois :-) (anytime you can of course)

Cheers!
