### ISSUE TITLE
Cannot install for spyder 4.2.3

### ISSUE THREAD

**Issue by kskollepara** [spyder-ide/spyder-vim#74]
I tried to install spyder-vim in two different ways:
`conda install spyder-vim -c spyder-ide`
which returned the `PackagesNotFoundError`
and 
`~/anaconda3/condabin/pip3 install spyder-vim`
This returned
> ERROR: Could not find a version that satisfies the requirement spyder-vim
> ERROR: No matching distribution found for spyder-vim

I have spyder 4.2.3 on an Ubuntu 18.04 system. Am I doing something wrong or is spyder-vim not meant for Spyder v4?

**Comment by ccordoba12** [comment]
Hey @kskollepara, thanks for your interest in this package. Unfortunately, we haven't released a first version of it yet because we haven't found someone to maintain it. That's why is not installable with conda.

Sorry for the inconvenience.
