### ISSUE TITLE
Update plugin to be compatible with Spyder 5

### ISSUE THREAD

**Issue by jmrichardson** [spyder-ide/spyder-vim#75]
I can't get VIM to work on spyder5.  Hoping that it can be enabled.  Thanks for any help!

**Comment by lmcj-xyz** [comment]
Same question here, I tried installing cloning the repo but it does not work. Might as well update README so that users don't try installing.

**Comment by ccordoba12** [comment]
Unfortunately we have a ton of work in Spyder and there's no one to help with this. Actually, all our external plugins (with the exception of Spyder-terminal) are in the same state right now.

Hopefully, we'll have some time to address that in the coming months.

**Comment by ashok-khanna** [comment]
At least change the readme, c'mon guys...
