### ISSUE TITLE
Continue to next/previous line for h or l keys is not a vim behavior

### ISSUE THREAD

**Issue by nevion** [spyder-ide/spyder-vim#8]
Hey - great to see this is quickly becoming useful after so long on the wishlist.

I just wanted to throw out that after updating to latest today, I note that holding h or l will continuously move through the buffer, and that is not a vim behavior.  Good job fixing #2 .

**Comment by Nodd** [comment]
Yes I noticed that, thanks for the report.
Do not hesitate to report any incoherencies you find in the future, I'm sure that it's not the only one.

**Comment by ccordoba12** [comment]
This was fixed by #15.
